### ISSUE TITLE
New release of WPS Office

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-office#2]
http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9704/wps-office_11.1.0.9711.XA_amd64.deb
https://wdl1.cache.wps.cn/wps/download/ep/Linux2019/9711/wps-office_11.1.0.9711_amd64.deb

version 11.1.0.9711

**Comment by pavroo** [comment]
Updated, thanks.
